# 室温や設置条件に応じて微調整可能
io:
  driver: simulator # simulator | lepton_spi | purethermal
  fps: 8.7
  width: 160
  height: 120
  # 実機用設定（必要なら）
  spi_bus: 0
  spi_device: 0
  usb_device: "/dev/video0"


thresholds:
  human_body_c_min: 24.0
  human_body_c_max: 39.0
  human_head_c_min: 29.0
  human_head_c_max: 39.0
  footprint_c_min: 17.0
  footprint_c_max: 22.0
  abnormal_low_c_max: 10.0
  abnormal_high_c_min: 60.0
  abnormal_high_c_max: 140.0
  abnormal_fire_c_min: 140.0


processing:
  bg_alpha: 0.02 # 背景の指数移動平均の学習率
  morph_kernel: 3 # 形態学演算のカーネル（正の奇数）
  min_region_area: 8 # ラベリングの最小ピクセル面積


viz:
  show: true
  save_dir: outputs
  font_scale: 0.5
  thickness: 1